cacheduringcompile:
    target: dev
    outputs:
        dev:
            type: redshift
            threads: 1
            host: localhost
            port: 5432
            user: postgres
            pass: mysecretpassword
            dbname: postgres
            schema: cacheduringcompile

